### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Patrick1020** [TouchedByDarkness/go-void-bot#1]
Hello , i get this error when i use auth 
![image](https://user-images.githubusercontent.com/78136826/190120861-27e8d99b-8564-4dc0-9788-e14ca1bf2a77.png)

**Comment by demlolollol** [comment]
i get a command from my powershell. some fatal error occured

**Comment by TouchedByDarkness** [comment]
authentication has been fixed in the latest version (1.8)
